# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe94131c27082e39e8e095dc735c65da"
name = "SHORT_ADDRESS_CODE"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping, write_shipping,read_customers"

[extensions.capabilities]
checkout_ui_visit_requested_address = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://shortcode.medicaloutfit.com"
prefix = "apps"
subpath = "address"